/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RosAdProgram.view;

import RosAdProgram.Controller.Controller;
import RosAdProgram.model.Model;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Вадим
 */
public class StatisticsGUI extends javax.swing.JFrame {

    /**
     * Creates new form StatisticsGUI
     */
    private final Model model;
    private Controller controller;
    
    public StatisticsGUI(Model model) {
        initComponents();
        this.model = model;
        model.setStatisticsGUIreference( this ); // при создании объекта StatisicsGUI в Model записывается его ссылка.
    }

    public void setValueButtomTable(int bitError, int byteError, int blockError, int currentByte, int currentBlock){
        DefaultTableModel tableModel = (DefaultTableModel) buttomTable.getModel();
        tableModel.setValueAt( bitError, 0, 2 );
        tableModel.setValueAt( byteError, 1, 2 );
        tableModel.setValueAt( blockError, 2, 2 );
        tableModel.setValueAt(( currentByte * 8), 0, 1 );
        tableModel.setValueAt( currentByte, 1, 1 );
        tableModel.setValueAt( currentBlock, 2, 1 );
    }
    
    // верхняя таблица. Обновляется по нажатию кнопки "Сохранить" окна Конфигурация
    public void setValueTopTable(){
        DefaultTableModel tableModel = (DefaultTableModel) topTable.getModel();
        tableModel.setValueAt(model.getBlockSize(), 3, 1);
        tableModel.setValueAt(model.getSpeed(), 4, 1);
        tableModel.setValueAt(model.getOpenPath(), 0, 1);
        tableModel.setValueAt(model.getSavePath(), 1, 1);
        tableModel.setValueAt(model.getFileSize(), 2, 1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        topTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        buttomTable = new javax.swing.JTable();
        compute = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        startButton = new javax.swing.JButton();

        setResizable(false);

        topTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Источник", null},
                {"Приемник", null},
                {"Размер файла, Байт", null},
                {"Размер блока, Байт", null},
                {"Скорость, Бод", null}
            },
            new String [] {
                "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        topTable.setToolTipText("");
        topTable.setShowHorizontalLines(true);
        topTable.setShowVerticalLines(true);
        jScrollPane1.setViewportView(topTable);
        if (topTable.getColumnModel().getColumnCount() > 0) {
            topTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        }
        topTable.getAccessibleContext().setAccessibleName("");

        buttomTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Биты", null, null, null},
                {"Байты", null, null, null},
                {"Блоки", null, null, null}
            },
            new String [] {
                "", "Всего", "Ошибки", "Коэффициент ошибок"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        buttomTable.setToolTipText("");
        buttomTable.setColumnSelectionAllowed(true);
        buttomTable.setShowHorizontalLines(true);
        buttomTable.setShowVerticalLines(true);
        jScrollPane2.setViewportView(buttomTable);
        buttomTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (buttomTable.getColumnModel().getColumnCount() > 0) {
            buttomTable.getColumnModel().getColumn(0).setResizable(false);
            buttomTable.getColumnModel().getColumn(1).setResizable(false);
            buttomTable.getColumnModel().getColumn(2).setResizable(false);
            buttomTable.getColumnModel().getColumn(3).setResizable(false);
            buttomTable.getColumnModel().getColumn(3).setPreferredWidth(400);
        }

        compute.setText("Рассчет");
        compute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeActionPerformed(evt);
            }
        });

        progressBar.setBackground(new java.awt.Color(0, 255, 0));
        progressBar.setForeground(java.awt.Color.orange);
        progressBar.setToolTipText("");
        progressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        progressBar.setStringPainted(true);

        startButton.setText("Связь");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(compute)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(startButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(compute)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void computeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeActionPerformed
        controller.computeButtonPressed();
        buttomTable.getModel().setValueAt( model.getErrorRatioArray()[0], 0, 3); // вывод в таблицу коэффициента ошибок по битам
        buttomTable.getModel().setValueAt( model.getErrorRatioArray()[1], 1, 3); // вывод в таблицу коэффициента ошибок по байтам
        buttomTable.getModel().setValueAt( model.getErrorRatioArray()[2], 2, 3); // вывод в таблицу коэффициента ошибок по блокам
    }//GEN-LAST:event_computeActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        model.copy();
    }//GEN-LAST:event_startButtonActionPerformed

    public void setControllerReference(Controller controller){
        this.controller = controller;
        model.getErrorRatioArray();
    }
    
    // устанавливает значение progressBar 
    public void setProgress(int number) {
        this.progressBar.setValue( number );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable buttomTable;
    private javax.swing.JButton compute;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton startButton;
    private javax.swing.JTable topTable;
    // End of variables declaration//GEN-END:variables
}
