/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RosAdProgram.view;
import RosAdProgram.model.Model;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author Вадим
 */
public class StatisticsGUI extends javax.swing.JFrame {

    /**
     * Creates new form StatisticsGUI
     */
    private final Model model;
    
    public StatisticsGUI(Model model) {
        this.model = model;
        initComponents();
        UIManager.put("nimbusOrange", new Color(29, 72, 242)); //RGB цвет прогресбара 
        model.setControllerReference( this ); // при создании объекта StatisicsGUI в Model записывается его ссылка.
    }
    
    // метод выставляет значение размера файла
    public void setFileSize(){
        long size = model.getFileSize(); // забираем из Model значение размера файла
        fileSizeLabel.setText(String.valueOf(size)); // конвертируем значение в строку и отображаем его в интерфейсе
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileSizeText = new javax.swing.JLabel();
        fileSizeLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        MistakeQuantityLabel = new javax.swing.JLabel();
        MistakeQuantityText = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        fileSizeText.setText("Размер файла, байт");

        fileSizeLabel.setText("(байт)");

        startButton.setText("Связь");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        MistakeQuantityLabel.setText("0");

        MistakeQuantityText.setText("Количество ошибочных блоков");

        progressBar.setBackground(new java.awt.Color(0, 255, 0));
        progressBar.setForeground(java.awt.Color.orange);
        progressBar.setToolTipText("");
        progressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        progressBar.setStringPainted(true);
        progressBar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                progressBarStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startButton)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fileSizeText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(MistakeQuantityText))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(fileSizeLabel)
                        .addGap(141, 141, 141)
                        .addComponent(MistakeQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MistakeQuantityText)
                    .addComponent(fileSizeText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MistakeQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileSizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(startButton)
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        model.copy();
    }//GEN-LAST:event_startButtonActionPerformed

    private void progressBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_progressBarStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_progressBarStateChanged

   // устанавливает значение progressBar 
    public void setProgress(int number) {
        this.progressBar.setValue( number );
    }
    // устанавливает количество ошибок
    public void setQuantityLabel(int quantity) {
        MistakeQuantityLabel.setText( String.valueOf(quantity) ); //
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MistakeQuantityLabel;
    private javax.swing.JLabel MistakeQuantityText;
    private javax.swing.JLabel fileSizeLabel;
    private javax.swing.JLabel fileSizeText;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables

}
